# Generated by Django 3.0.6 on 2020-05-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='wadmin',
        ),
    ]
